import type { DevelopmentContent } from "../../types";

export const liveCacupe: DevelopmentContent = {
  id: "live-cacupe",
  slug: "live-cacupe",
  name: "Live Cacupé",
  projectName: "Live Cacupé",
  formLabel: "Live Cacupé — Cacupé",
  city: "Florianópolis",
  neighborhood: "Cacupé",
  status: "Pronto para morar",
  logoImage: "/content/developments/live-cacupe/logo/logo-live-cacupe.png",
  discountLabel: "A partir de",
  originalPrice: 0,
  discountedPrice: 1346063,
  typology: "Apartamento, Loft, Duplex, Garden",
  area: "76 m² a 141 m² privativos",
  highlights: [
    "Vista permanente para o mar",
    "Arquitetura biofílica",
    "Pronto para morar",
    "Rooftop com piscina",
  ],
  cta: "Quero conhecer",
  isActive: true,
  displayOrder: 1,
  coverImage: "/content/developments/live-cacupe/cover/foto-lumis.webp",
  description:
    "Residencial de alto padrão em Cacupé com vista para o mar, arquitetura biofílica e lazer completo. O privilégio de viver em um refúgio exclusivo com o pôr do sol mais bonito da ilha.",
  builder: "Lumis Construtora",
  deliveryDate: "Pronto para morar",
  bedrooms: "1 a 3 quartos",
  suites: "1 suíte",
  address: "Estrada Haroldo Soares Glavan 566 — Cacupé, Florianópolis/SC",
  latitude: -27.5307,
  longitude: -48.5046,
  locationDescription:
    "Bairro nobre, reservado e tranquilo, a 3 min da SC-401, 10 min de Jurerê Internacional e 15 min do centro de Florianópolis.",
  apartmentFeatures: [
    "Persianas motorizadas",
    "Tomadas USB nos dormitórios",
    "Piso vinílico nos quartos",
    "Porcelanato na área social",
    "Acesso digital nas unidades",
    "Churrasqueira a carvão",
    "Hobby box",
    "Vasos com acionamento duplo",
  ],
  condoFeatures: [
    "Rooftop com piscina vista mar",
    "Ofurô privativo",
    "Wine pub",
    "Sala de yoga",
    "Academia completa",
    "Smart lounge",
    "Coworking",
    "Salão de festas interno e externo",
    "Brinquedoteca e playground",
    "Pet place",
    "Sauna",
    "Controle de acesso digital",
    "Infraestrutura para carro elétrico",
    "Mini market interno",
    "Smart locker",
    "Wi-fi nas áreas de lazer",
    "Reaproveitamento de água da chuva",
  ],
  galleryImages: [
    { title: "Piscina no Rooftop com Vista Mar", url: "/content/developments/live-cacupe/hero/piscina-no-rooftop.webp" },
    { title: "Wine Pub com Ofurô", url: "/content/developments/live-cacupe/gallery/wine-pub-externo-com-ofuro.webp" },
    { title: "Sala de Yoga", url: "/content/developments/live-cacupe/gallery/Sala-Yoga.webp" },
    { title: "Academia", url: "/content/developments/live-cacupe/gallery/academia.webp" },
    { title: "Sala", url: "/content/developments/live-cacupe/gallery/sala.webp" },
    { title: "Cozinha", url: "/content/developments/live-cacupe/gallery/cozinha.webp" },
    { title: "Quarto Casal", url: "/content/developments/live-cacupe/gallery/quarto-casal.webp" },
    { title: "Quarto", url: "/content/developments/live-cacupe/gallery/quarto.webp" },
    { title: "Salão de Festas Externo", url: "/content/developments/live-cacupe/gallery/salao-de-festa-externo.webp" },
    { title: "Salão de Festas Interno", url: "/content/developments/live-cacupe/gallery/salao-de-festa-interno.webp" },
    { title: "Sauna", url: "/content/developments/live-cacupe/gallery/sauna.webp" },
    { title: "Coworking", url: "/content/developments/live-cacupe/gallery/coworking.webp" },
    { title: "Espaço Kids", url: "/content/developments/live-cacupe/gallery/espaco-kids.png" },
  ],
  floorPlans: [],
  documents: [],
};
